import { BannerBlockStyle } from "~/application/dtos/marketing/BannerBlockDto";
import { CommunityBlockStyle } from "~/application/dtos/marketing/CommunityBlockDto";
import { FaqBlockStyle } from "~/application/dtos/marketing/FaqBlockDto";
import { FeaturesBlockStyle } from "~/application/dtos/marketing/FeaturesBlockDto";
import { FooterBlockDto, FooterBlockStyle } from "~/application/dtos/marketing/FooterBlockDto";
import { GalleryBlockStyle } from "~/application/dtos/marketing/GalleryBlockDto";
import { HeaderBlockDto, HeaderBlockStyle } from "~/application/dtos/marketing/HeaderBlockDto";
import { HeroBlockStyle } from "~/application/dtos/marketing/HeroBlockDto";
import { LogoCloudsBlockStyle } from "~/application/dtos/marketing/LogoCloudsBlockDto";
import { NewsletterBlockStyle } from "~/application/dtos/marketing/NewsletterBlockDto";
import { PageBlockDto } from "~/application/dtos/marketing/PageBlockDto";
import { TestimonialsBlockStyle } from "~/application/dtos/marketing/TestimonialsBlockDto";
import { VideoBlockStyle } from "~/application/dtos/marketing/VideoBlockDto";

const defaultStyles = {
  banner: BannerBlockStyle.top,
  header: HeaderBlockStyle.simple,
  footer: FooterBlockStyle.columns,
  hero: HeroBlockStyle.simple,
  gallery: GalleryBlockStyle.carousel,
  logoClouds: LogoCloudsBlockStyle.simple,
  video: VideoBlockStyle.simple,
  community: CommunityBlockStyle.simple,
  testimonials: TestimonialsBlockStyle.simple,
  features: FeaturesBlockStyle.list,
  newsletter: NewsletterBlockStyle.rightForm,
  faq: FaqBlockStyle.simple,
};

export function saasrockLandingPage() {
  const blocks: PageBlockDto[] = [
    // Banner
    {
      banner: {
        style: defaultStyles.banner,
        text: "Build your MVP in less than a week 🚀",
        cta: [
          { text: "Try Enterprise", href: "https://enterprise.saasrock.com/?ref=remix-page-blocks-saasrock-template-banner", target: "_blank" },
          { text: "Try Core", href: "https://demo.saasrock.com/?ref=remix-page-blocks-saasrock-template-banner", target: "_blank" },
        ],
      },
    },
    // Header
    {
      header: defaultHeader,
    },
    // Hero
    {
      hero: {
        style: defaultStyles.hero,
        headline: "The One-Man SaaS Framework",
        subheadline:
          "Quick start your MVP with out-of-the-box SaaS features like Authentication, Pricing & Subscriptions, Admin & App portals, Entity Builder (Autogenerated CRUD, API, Webhooks, Permissions, Audit-trails...), Blogging, CRM, Email Marketing, and more. Don't reinvent the wheel, again.",
        cta: [
          {
            text: "Get a GitHub invite",
            href: "https://saasrock.com/pricing?ref=remix-page-blocks-saasrock-template-hero",
            target: "_blank",
            isPrimary: true,
          },
          {
            text: "Documentation",
            href: "https://saasrock.com/docs?ref=remix-page-blocks-saasrock-template-hero",
            target: "_blank",
            isPrimary: false,
          },
        ],
        topText: {
          text: "Build → Market → Manage your SaaS",
        },
        bottomText: {
          link: {
            text: "This site uses v0.7.0 Enterprise Edition",
            href: "https://saasrock.com/changelog?ref=remix-page-blocks-saasrock-template-hero",
            target: "_blank",
          },
        },
      },
    },
    // Logo Clouds
    {
      logoClouds: {
        style: defaultStyles.logoClouds,
        headline: "Leverage the power of web fundamentals, utility-first CSS, and a top-tier ORM.",
        logos: [
          {
            alt: "Tailwind CSS",
            href: "https://tailwindcss.com/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/tailwindcss-G3OQBAVI.png",
            srcDark: "",
          },
          {
            alt: "TypeScript",
            href: "https://www.typescriptlang.org/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/typescript-KI4PEQV2.png",
            srcDark: "",
          },
          {
            alt: "Prisma",
            href: "https://prisma.io/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/prisma-ATY77GXX.png",
            srcDark: "https://saasrock.com/build/_assets/prisma-dark-3FBYDJ4J.png",
          },
          {
            alt: "Remix",
            href: "https://remix.run/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/remix-4ESNCVZ5.png",
            srcDark: "https://saasrock.com/build/_assets/remix-dark-U2ASPSOI.png",
          },
          {
            alt: "React",
            href: "https://reactjs.org/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/react-7YBNQQA7.png",
            srcDark: "",
          },
          {
            alt: "Stripe",
            href: "https://stripe.com/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/stripe-DH3K2AKH.png",
            srcDark: "",
          },
          {
            alt: "Postmark",
            href: "https://postmarkapp.com/?ref=remix-page-blocks",
            src: "https://saasrock.com/build/_assets/postmark-YFRKRMUJ.png",
            srcDark: "",
          },
        ],
      },
    },
    // Gallery
    {
      gallery: {
        style: defaultStyles.gallery,
        topText: "Don't build from scratch",
        headline: "+90 SaaS-ready pages",
        subheadline:
          "Marketing pages (Landing, Blog, Pricing), App pages (Dashboard, Account Settings), and Admin pages (Tenant/Users, Pricing, Entity Builder, Blog posts, CRM, Email marketing, and more).",
        images: [
          {
            title: "Admin Dashboard",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/dashboard.png",
          },
          {
            title: "Users",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/users.png",
          },
          {
            title: "Accounts",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/tenants.png",
          },
          {
            title: "Blogging",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/blog.png",
          },
          {
            title: "Entities",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/entities.png",
          },
          {
            title: "Admin API Keys",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/api-keys.png",
          },
          {
            title: "Admin API Logs",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/api-logs.png",
          },
          {
            title: "Admin Audit Trails",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/audit-trails.png",
          },
          {
            title: "Set up Pricing Plans",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/setup-pricing.png",
          },
          {
            title: "Set up Email Templates",
            src: "https://yahooder.sirv.com/saasrock/features/admin-portal/setup-emails.png",
          },
          {
            title: "App Dashboard",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/dashboard.png",
          },
          {
            title: "Command Palette",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/command-palette.png",
          },
          {
            title: "Profile",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/profile.png",
          },
          {
            title: "Members",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/members.png",
          },
          {
            title: "Subscription",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/subscription.png",
          },
          {
            title: "Linked Accounts",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/linked-accounts.png",
          },
          {
            title: "Account",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/account.png",
          },
          {
            title: "API Keys",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/api-keys.png",
          },
          {
            title: "API Logs",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/api-logs.png",
          },
          {
            title: "Tenant Audit Trails",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/audit-trails.png",
          },
          {
            title: "Switch Account",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/select-account.png",
          },
          {
            title: "New Account",
            src: "https://yahooder.sirv.com/saasrock/features/app-portal/new-account.png",
          },
          {
            title: "Login",
            src: "https://yahooder.sirv.com/saasrock/features/authentication/login.png",
          },
          {
            title: "Register",
            src: "https://yahooder.sirv.com/saasrock/features/authentication/register.png",
          },
          {
            title: "Forgot Password",
            src: "https://yahooder.sirv.com/saasrock/features/authentication/forgot-password.png",
          },
          {
            title: "Reset",
            src: "https://yahooder.sirv.com/saasrock/features/authentication/reset-password.png",
          },
          {
            title: "Pricing",
            src: "https://yahooder.sirv.com/saasrock/features/subscriptions/pricing.png",
          },
          {
            title: "My Subscription",
            src: "https://yahooder.sirv.com/saasrock/features/subscriptions/my-subscription.png",
          },
          {
            title: "Tenant Subscription",
            src: "https://yahooder.sirv.com/saasrock/features/subscriptions/tenant-subscription.png",
          },
          {
            title: "Subscription Plans",
            src: "https://yahooder.sirv.com/saasrock/features/subscriptions/subscription-plans.png",
          },
          {
            title: "Create Subscription Plan",
            src: "https://yahooder.sirv.com/saasrock/features/subscriptions/create-subscription-plan.png",
          },
          {
            title: "Blog",
            src: "https://yahooder.sirv.com/saasrock/features/blogging/blog.png",
          },
          {
            title: "Blog Posts",
            src: "https://yahooder.sirv.com/saasrock/features/blogging/blog-posts.png",
          },
          {
            title: "New Blog Post",
            src: "https://yahooder.sirv.com/saasrock/features/blogging/new-blog-post.png",
          },
          {
            title: "Blog Post",
            src: "https://yahooder.sirv.com/saasrock/features/blogging/blog-post.png",
          },
          {
            title: "Admin Audit Trails",
            src: "https://yahooder.sirv.com/saasrock/features/audit-trails/admin.png",
          },
          {
            title: "Tenant Audit Trails",
            src: "https://yahooder.sirv.com/saasrock/features/audit-trails/tenant.png",
          },
          {
            title: "API Audit Trails",
            src: "https://yahooder.sirv.com/saasrock/features/audit-trails/api.png",
          },
          {
            title: "Entities",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/entities.png",
          },
          {
            title: "Entity Details",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/entity-details.png",
          },
          {
            title: "Entity Properties",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/properties.png",
          },
          {
            title: "New Property",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/new-property.png",
          },
          {
            title: "Admin Entity Rows View",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/admin-rows-logs.png",
          },
          {
            title: "Admin Entity Rows Logs",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/admin-rows-view.png",
          },
          {
            title: "Entity Webhooks",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/webhooks.png",
          },
          {
            title: "Entity API Docs (UNDER CONSTRUCTION)",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/api.png",
          },
          {
            title: "Autogenerated Table View",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/table-view.png",
          },
          {
            title: "Autogenerated Create Form",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/create-form.png",
          },
          {
            title: "Autogenerated Detail/Edit View and Form",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/details-view-and-form.png",
          },
          {
            title: "Tenant Entity Row Logs",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/rows-logs.png",
          },
          {
            title: "API Usage",
            src: "https://yahooder.sirv.com/saasrock/features/entity-builder/api-usage.png",
          },
          {
            title: "New Entity Webhook",
            src: "https://yahooder.sirv.com/saasrock/features/webhooks/new-webhook.png",
          },
          {
            title: "Webhooks by Zapier Set up",
            src: "https://yahooder.sirv.com/saasrock/features/webhooks/zapier.png",
          },
          {
            title: "Add created entity rows to Google Sheets",
            src: "https://yahooder.sirv.com/saasrock/features/webhooks/google-sheets.png",
          },
          {
            title: "GET - Get all entity rows",
            src: "https://yahooder.sirv.com/saasrock/features/api/get.png",
          },
          {
            title: "POST - Create entity row",
            src: "https://yahooder.sirv.com/saasrock/features/api/post.png",
          },
          {
            title: "GET - Get entity row",
            src: "https://yahooder.sirv.com/saasrock/features/api/get-id.png",
          },
          {
            title: "PUT - Update entity row",
            src: "https://yahooder.sirv.com/saasrock/features/api/put.png",
          },
          {
            title: "DELETE - Delete entity row",
            src: "https://yahooder.sirv.com/saasrock/features/api/delete.png",
          },
          {
            title: "API Logs",
            src: "https://yahooder.sirv.com/saasrock/features/api/logs.png",
          },
          {
            title: "Roles",
            src: "https://user-images.githubusercontent.com/8606530/174460485-0c17e2bb-1eb7-490b-8e6e-1546770401d7.png",
          },
          {
            title: "Permissions",
            src: "https://user-images.githubusercontent.com/8606530/174460558-589ac602-2061-4fe6-a9a0-e734f75269b4.png",
          },
          {
            title: "Set Admin Roles",
            src: "https://user-images.githubusercontent.com/8606530/174461740-65b264ce-38f4-4e82-a6a9-77bd123a0deb.png",
          },
          {
            title: "Set Account User Roles",
            src: "https://user-images.githubusercontent.com/8606530/174460587-ef90a695-1fcd-4ddb-af9b-641c27a73481.png",
          },
          {
            title: "Groups",
            src: "https://user-images.githubusercontent.com/8606530/174460615-a20dbedc-bdbf-4248-91dc-f86002aac812.png",
          },
          {
            title: "Row visibility - Private (only you)",
            src: "https://user-images.githubusercontent.com/8606530/174460688-7069d654-ce39-4b55-8777-69e17a69c315.png",
          },
          {
            title: "Row visibility - Share to Account Members",
            src: "https://user-images.githubusercontent.com/8606530/174460695-4de0bf14-7e95-46e0-9852-9cacb92f55fa.png",
          },
          {
            title: "Row visibility - Share to Specific Groups",
            src: "https://user-images.githubusercontent.com/8606530/174460699-9a149df9-7406-4fe6-923d-9cb04560395d.png",
          },
          {
            title: "Row visibility - Share to Specific Users",
            src: "https://user-images.githubusercontent.com/8606530/174460705-ec683416-2ac1-4efb-91da-4de152e88459.png",
          },
          {
            title: "Row visibility - Set Public",
            src: "https://user-images.githubusercontent.com/8606530/174460711-ac9beeca-6af9-4a6e-959d-5b03a744b9ee.png",
          },
          {
            title: "Public row view",
            src: "https://user-images.githubusercontent.com/8606530/174460727-d2a10e3e-70a1-46c1-b5f2-e558ee6e840a.png",
          },
          {
            title: "Events Route",
            src: "https://yahooder.sirv.com/saasrock/features/events-and-webhooks/events.png",
          },
          {
            title: "Event",
            src: "https://yahooder.sirv.com/saasrock/features/events-and-webhooks/event.png",
          },
          {
            title: "Event Details",
            src: "https://yahooder.sirv.com/saasrock/features/events-and-webhooks/event-details.png",
          },
        ],
      },
    },
    // Video
    {
      video: {
        style: defaultStyles.video,
        headline: "Low-code CRUD on steroids with the Entity Builder 🎥",
        subheadline: "Watch the latest video about the new Entity Builder and how to use it to build a CRUD application in minutes with v0.7.0 👇.",
        src: "https://www.youtube.com/embed/5wKe0T7k4Zk",
      },
    },
    // Community
    {
      community: {
        style: defaultStyles.community,
        headline: "The SaasRock Community",
        subheadline: "We're all looking to build successful SaaS applications.",
        type: "github",
        members: [],
        cta: [
          {
            text: "Subscribe",
            href: "https://saasrock.com/pricing?ref=remix-page-blocks-saasrock-template-community",
          },
          {
            text: "Join Discord",
            href: "https://discord.gg/KMkjU2BFn9",
          },
          {
            text: "Youtube channel",
            href: "https://www.youtube.com/channel/UCdXy3FPDHxP-b7NhPspt6cQ",
          },
        ],
      },
    },
    // Testimonials
    {
      testimonials: {
        style: defaultStyles.testimonials,
        headline: "Don't take our word for it.",
        subheadline: ``,
        items: [
          {
            role: "CEO",
            company: "Piloterr",
            companyUrl: "https://www.piloterr.com/",
            logoLightMode: "https://yahooder.sirv.com/saasrock/testimonials/piloterr-light.png",
            logoDarkMode: "https://yahooder.sirv.com/saasrock/testimonials/piloterr-dark.png",
            name: "Josselin Liebe",
            personalWebsite: "https://josselinlie.be/",
            avatar: "https://avatars.githubusercontent.com/u/15314417?v=4",
            quote: "You've already solved 90% of my problems with your project :)",
          },
        ],
      },
    },
    // Features #1
    {
      features: {
        style: FeaturesBlockStyle.cards,
        topText: "Rock-solid features 🪨",
        headline: "A rock-solid starter kit",
        subheadline: "Everything you need to start to build an MVP, or to build a whole SaaS application in a few weeks.",
        columns: 3,
        items: [
          {
            name: "Admin Portal",
            description: "Manage your SaaS tenants, users, blog, entities, audit trails, API Keys, pricing, and emails.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 4 4 L 4 5 L 4 28 L 28 28 L 28 4 L 4 4 z M 6 6 L 26 6 L 26 10 L 6 10 L 6 6 z M 7 7 L 7 9 L 9 9 L 9 7 L 7 7 z M 10 7 L 10 9 L 12 9 L 12 7 L 10 7 z M 13 7 L 13 9 L 25 9 L 25 7 L 13 7 z M 6 12 L 26 12 L 26 26 L 6 26 L 6 12 z M 17.5 14 C 15.567 14 14 15.567 14 17.5 C 14 18.079 14.153344 18.617609 14.402344 19.099609 C 12.906344 20.636609 11.594969 21.990969 11.292969 22.292969 C 11.103969 22.481969 11 22.733 11 23 C 11 23.267 11.103969 23.518031 11.292969 23.707031 C 11.481969 23.896031 11.733 24 12 24 C 12.267 24 12.518031 23.896031 12.707031 23.707031 C 12.993031 23.421031 14.264484 22.18675 15.896484 20.59375 C 16.378484 20.84475 16.919 21 17.5 21 C 19.433 21 21 19.433 21 17.5 C 21 16.899 20.833406 16.341656 20.566406 15.847656 L 18 18.414062 L 16.585938 17 L 19.152344 14.433594 C 18.658344 14.166594 18.101 14 17.5 14 z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/admin-portal" },
          },
          {
            name: "App Portal",
            description: "Your customer's portal with Dashboard and Settings pages: Profile, Members, Subscription, API Keys...",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 4 4 L 4 28 L 19.273438 28 C 18.475388 29.135328 18 30.512091 18 32 L 20 32 C 20 29.226334 22.226334 27 25 27 C 27.773666 27 30 29.226334 30 32 L 32 32 C 32 29.371676 30.478925 27.157432 28.326172 25.960938 C 28.784265 25.651654 29.250971 25.337329 29.634766 25.005859 C 30.71961 24.068918 31.488281 23.136719 31.488281 23.136719 L 32.005859 22.507812 L 31.496094 21.873047 C 31.496094 21.873047 30.746239 20.936055 29.667969 19.996094 C 29.179992 19.570709 28.617107 19.131891 28 18.767578 L 28 4 L 4 4 z M 6 6 L 26 6 L 26 10 L 6 10 L 6 6 z M 7 7 L 7 9 L 9 9 L 9 7 L 7 7 z M 10 7 L 10 9 L 12 9 L 12 7 L 10 7 z M 13 7 L 13 9 L 25 9 L 25 7 L 13 7 z M 6 12 L 26 12 L 26 18.037109 C 25.835538 18.016795 25.670308 18 25.5 18 C 23.026562 18 21 20.026562 21 22.5 C 21 23.690376 21.48732 24.763027 22.25 25.570312 C 21.963342 25.693691 21.689462 25.840998 21.423828 26 L 6 26 L 6 12 z M 25.5 20 C 26.216698 20 27.424286 20.693868 28.353516 21.503906 C 28.92056 21.998216 29.043908 22.183152 29.320312 22.494141 C 29.037323 22.806248 28.905535 22.995452 28.328125 23.494141 C 27.386719 24.307199 26.16357 25 25.5 25 C 24.107438 25 23 23.892562 23 22.5 C 23 21.107438 24.107438 20 25.5 20 z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/app-portal" },
          },
          {
            name: "Authentication",
            description: "Login, Register, and Forgot/Reset password auth pages + Multi-tenancy support.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 16 3 C 12.144531 3 9 6.144531 9 10 L 9 13 L 6 13 L 6 29 L 26 29 L 26 13 L 23 13 L 23 10 C 23 6.144531 19.855469 3 16 3 Z M 16 5 C 18.773438 5 21 7.226563 21 10 L 21 13 L 11 13 L 11 10 C 11 7.226563 13.226563 5 16 5 Z M 8 15 L 24 15 L 24 27 L 8 27 Z M 12 20 C 11.449219 20 11 20.449219 11 21 C 11 21.550781 11.449219 22 12 22 C 12.550781 22 13 21.550781 13 21 C 13 20.449219 12.550781 20 12 20 Z M 16 20 C 15.449219 20 15 20.449219 15 21 C 15 21.550781 15.449219 22 16 22 C 16.550781 22 17 21.550781 17 21 C 17 20.449219 16.550781 20 16 20 Z M 20 20 C 19.449219 20 19 20.449219 19 21 C 19 21.550781 19.449219 22 20 22 C 20.550781 22 21 21.550781 21 21 C 21 20.449219 20.550781 20 20 20 Z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/authentication" },
          },
          {
            name: "Subscriptions",
            description: "Subscription plans/prices with Flat-rate and Per-seat pricing models.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 5 6 C 3.355469 6 2 7.355469 2 9 L 2 23 C 2 24.644531 3.355469 26 5 26 L 27 26 C 28.644531 26 30 24.644531 30 23 L 30 9 C 30 7.355469 28.644531 6 27 6 Z M 5 8 L 27 8 C 27.566406 8 28 8.433594 28 9 L 28 23 C 28 23.566406 27.566406 24 27 24 L 5 24 C 4.433594 24 4 23.566406 4 23 L 4 9 C 4 8.433594 4.433594 8 5 8 Z M 12 10 L 10.167969 14 L 5.691406 14.582031 L 9 17.597656 L 8 22 L 12 19.75 L 16 22 L 15 17.597656 L 18.308594 14.582031 L 13.832031 14 Z M 12 14.800781 L 12.015625 14.832031 L 12.472656 15.839844 L 13.574219 15.984375 L 13.769531 16.011719 L 13.652344 16.117188 L 12.789063 16.902344 L 13.046875 18.039063 L 13.050781 18.046875 L 12.980469 18.007813 L 12 17.457031 L 11.019531 18.007813 L 10.949219 18.046875 L 10.953125 18.039063 L 11.207031 16.902344 L 10.347656 16.117188 L 10.226563 16.011719 L 10.425781 15.984375 L 11.523438 15.839844 L 11.984375 14.832031 Z M 18 20 L 18 22 L 20 22 L 20 20 Z M 21 20 L 21 22 L 23 22 L 23 20 Z M 24 20 L 24 22 L 26 22 L 26 20 Z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/subscriptions" },
          },
          {
            name: "Blogging",
            description: "Publish your blog posts with SEO-ready features.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 14.519531 4.0097656 C 14.239531 3.9997656 14 4.2295312 14 4.5195312 L 14 6.5 C 14 6.78 14.22 7 14.5 7 L 14.5 7.0195312 C 20.73 7.2595312 25.740469 12.27 25.980469 18.5 L 26 18.5 C 26 18.78 26.22 19 26.5 19 L 28.480469 19 C 28.770469 19 29.000234 18.760469 28.990234 18.480469 C 28.720234 10.620469 22.379531 4.2797656 14.519531 4.0097656 z M 14.519531 9.0097656 C 14.239531 8.9997656 14 9.2395313 14 9.5195312 L 14 11.5 C 14 11.78 14.22 12 14.5 12 L 14.5 12.029297 C 17.97 12.259297 20.740703 15.03 20.970703 18.5 L 21 18.5 C 21 18.78 21.22 19 21.5 19 L 23.480469 19 C 23.760469 19 24.000234 18.760469 23.990234 18.480469 C 23.720234 13.380469 19.619531 9.2797656 14.519531 9.0097656 z M 5.5 10 C 5.22 10 5 10.22 5 10.5 L 5 21.5 C 5 25.08 7.92 28 11.5 28 C 15.08 28 18 25.08 18 21.5 C 18 17.92 15.08 15 11.5 15 C 11.22 15 11 15.22 11 15.5 L 11 18.5 C 11 18.78 11.22 19 11.5 19 C 12.88 19 14 20.12 14 21.5 C 14 22.88 12.88 24 11.5 24 C 10.12 24 9 22.88 9 21.5 L 9 10.5 C 9 10.22 8.78 10 8.5 10 L 5.5 10 z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/blogging" },
          },
          {
            name: "Audit Trails",
            description: "Track the SaaS application usage with Created, Updated, and Deleted events.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 6 3 L 6 10 L 8 10 L 8 5 L 24 5 L 24 10 L 26 10 L 26 3 L 6 3 z M 8 12 L 8 20 L 12 20 L 12 18 L 10 18 L 10 12 L 8 12 z M 15.5 12 C 14.116667 12 13 13.116667 13 14.5 L 13 17.5 C 13 18.883333 14.116667 20 15.5 20 C 16.883333 20 18 18.883333 18 17.5 L 18 14.5 C 18 13.116667 16.883333 12 15.5 12 z M 21.5 12 C 20.116667 12 19 13.116667 19 14.5 L 19 17.5 C 19 18.883333 20.116667 20 21.5 20 L 24 20 L 24 16 L 22 16 L 22 17 L 22 18 L 21.5 18 C 21.283333 18 21 17.716667 21 17.5 L 21 14.5 C 21 14.283333 21.283333 14 21.5 14 C 21.716667 14 22 14.283333 22 14.5 L 22 15 L 24 15 L 24 14.5 C 24 13.116667 22.883333 12 21.5 12 z M 15.5 14 C 15.716667 14 16 14.283333 16 14.5 L 16 17.5 C 16 17.716667 15.716667 18 15.5 18 C 15.283333 18 15 17.716667 15 17.5 L 15 14.5 C 15 14.283333 15.283333 14 15.5 14 z M 6 22 L 6 29 L 26 29 L 26 22 L 24 22 L 24 27 L 8 27 L 8 22 L 6 22 z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/audit-trails" },
          },
          {
            name: "Entity Builder",
            description: "Create custom entities/properties with autogenerated views, forms, API, audit trails, and webhooks.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 5 5 L 5 27 L 27 27 L 27 5 Z M 7 7 L 25 7 L 25 25 L 7 25 Z M 14 9 L 14 15 L 23 15 L 23 9 Z M 9 11 L 9 13 L 12 13 L 12 11 Z M 16 11 L 21 11 L 21 13 L 16 13 Z M 14 17 L 14 23 L 23 23 L 23 17 Z M 9 19 L 9 21 L 12 21 L 12 19 Z M 16 19 L 21 19 L 21 21 L 16 21 Z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/entity-builder" },
          },
          {
            name: "API",
            description: "Let your SaaS users use the API to integrate with other services.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 16.03125 3 C 14.8125 3 13.578125 3.160156 12.375 3.5 L 11.59375 3.71875 L 11.65625 4.5 C 11.703125 5.332031 11.292969 6.175781 10.5 6.625 C 9.703125 7.078125 8.78125 6.996094 8.0625 6.53125 L 7.40625 6.09375 L 6.8125 6.65625 C 5.011719 8.367188 3.777344 10.523438 3.1875 12.84375 L 3 13.625 L 3.71875 13.96875 C 4.488281 14.351563 5 15.109375 5 16 C 5 16.890625 4.488281 17.652344 3.71875 18.03125 L 3 18.375 L 3.1875 19.15625 C 3.480469 20.296875 3.929688 21.453125 4.5625 22.53125 C 5.195313 23.609375 5.957031 24.527344 6.8125 25.34375 L 7.40625 25.90625 L 8.0625 25.46875 C 8.753906 25.019531 9.632813 24.949219 10.40625 25.34375 L 10.5 25.375 C 11.292969 25.828125 11.707031 26.664063 11.65625 27.5 L 11.59375 28.28125 L 12.375 28.5 C 13.554688 28.832031 14.773438 29.007813 16 29 C 17.226563 29 18.449219 28.828125 19.625 28.5 L 20.40625 28.28125 L 20.34375 27.46875 C 20.292969 26.636719 20.703125 25.828125 21.5 25.375 C 22.292969 24.921875 23.21875 24.972656 23.9375 25.4375 L 24.59375 25.875 L 25.1875 25.34375 C 26.042969 24.527344 26.804688 23.578125 27.4375 22.5 C 27.988281 21.5625 28.335938 20.582031 28.625 19.59375 L 28.6875 19.59375 L 28.6875 19.5625 C 28.691406 19.554688 28.710938 19.484375 28.71875 19.46875 C 28.742188 19.410156 28.765625 19.335938 28.8125 19.15625 L 29 18.375 L 28.28125 18.03125 C 27.511719 17.648438 27 16.890625 27 16 C 27 15.109375 27.511719 14.347656 28.28125 13.96875 L 29 13.625 L 28.8125 12.84375 C 28.519531 11.703125 28.070313 10.578125 27.4375 9.5 C 26.804688 8.421875 26.046875 7.472656 25.1875 6.65625 L 24.59375 6.09375 L 23.9375 6.53125 C 23.21875 6.996094 22.296875 7.078125 21.5 6.625 C 20.703125 6.171875 20.292969 5.332031 20.34375 4.5 L 20.40625 3.71875 L 19.625 3.5 C 18.460938 3.171875 17.25 3 16.03125 3 Z M 16.03125 5 C 16.886719 5 17.734375 5.152344 18.5625 5.34375 C 18.769531 6.558594 19.34375 7.6875 20.5 8.34375 C 21.664063 9.003906 22.960938 8.933594 24.125 8.5 C 24.710938 9.109375 25.277344 9.746094 25.71875 10.5 C 26.15625 11.246094 26.414063 12.050781 26.65625 12.84375 C 25.710938 13.625 25 14.683594 25 16 C 25 17.316406 25.710938 18.375 26.65625 19.15625 C 26.414063 19.949219 26.15625 20.757813 25.71875 21.5 C 25.273438 22.257813 24.71875 22.886719 24.125 23.5 C 22.957031 23.0625 21.664063 22.964844 20.5 23.625 C 19.351563 24.277344 18.777344 25.421875 18.5625 26.625 C 17.726563 26.816406 16.863281 27 16 27 C 15.132813 27.007813 14.269531 26.847656 13.4375 26.65625 C 13.230469 25.445313 12.65625 24.3125 11.5 23.65625 C 10.335938 22.996094 9.039063 23.066406 7.875 23.5 C 7.289063 22.890625 6.722656 22.253906 6.28125 21.5 C 5.84375 20.753906 5.554688 19.984375 5.3125 19.1875 C 6.277344 18.40625 7 17.332031 7 16 C 7 14.675781 6.269531 13.625 5.3125 12.84375 C 5.804688 11.230469 6.699219 9.761719 7.90625 8.5 C 9.0625 8.921875 10.347656 8.996094 11.5 8.34375 C 12.65625 7.6875 13.226563 6.554688 13.4375 5.34375 C 14.300781 5.140625 15.164063 5 16.03125 5 Z M 10.21875 12 L 10 12.6875 L 8.0625 18.6875 L 8 18.84375 L 8 20 L 10 20 L 10 19.125 L 10.03125 19 L 11.96875 19 L 12 19.125 L 12 20 L 14 20 L 14 18.84375 L 13.9375 18.6875 L 12 12.6875 L 11.78125 12 Z M 15 12 L 15 20 L 17 20 L 17 18 C 18.644531 18 20 16.644531 20 15 C 20 13.355469 18.644531 12 17 12 Z M 21 12 L 21 20 L 23 20 L 23 12 Z M 17 14 C 17.566406 14 18 14.433594 18 15 C 18 15.566406 17.566406 16 17 16 Z M 11 16.0625 L 11.3125 17 L 10.6875 17 Z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/api" },
          },
          {
            name: "Entity Webhooks",
            description: "Connect with Zappier, hence with +4,000 popular applications like Google Drive, Notion, Asana...",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 16 3 C 12.144531 3 9 6.144531 9 10 C 9 12.09375 10.035156 13.871094 11.5 15.15625 L 9.40625 19.03125 C 9.269531 19.011719 9.140625 19 9 19 C 7.355469 19 6 20.355469 6 22 C 6 23.644531 7.355469 25 9 25 C 10.644531 25 12 23.644531 12 22 C 12 21.203125 11.671875 20.476563 11.15625 19.9375 L 14 14.65625 L 13.25 14.15625 C 11.902344 13.261719 11 11.746094 11 10 C 11 7.226563 13.226563 5 16 5 C 18.773438 5 21 7.226563 21 10 C 21 10.585938 20.902344 11.136719 20.71875 11.65625 L 22.59375 12.34375 C 22.855469 11.613281 23 10.816406 23 10 C 23 6.144531 19.855469 3 16 3 Z M 16 7 C 14.355469 7 13 8.355469 13 10 C 13 11.644531 14.355469 13 16 13 C 16.140625 13 16.269531 12.988281 16.40625 12.96875 L 19.15625 17.34375 L 19.65625 18.15625 L 20.5 17.65625 C 21.234375 17.230469 22.085938 17 23 17 C 25.773438 17 28 19.226563 28 22 C 28 24.773438 25.773438 27 23 27 C 21.511719 27 20.195313 26.367188 19.28125 25.34375 L 17.78125 26.65625 C 19.0625 28.085938 20.933594 29 23 29 C 26.855469 29 30 25.855469 30 22 C 30 18.144531 26.855469 15 23 15 C 22.078125 15 21.277344 15.363281 20.46875 15.6875 L 18.1875 12.03125 C 18.6875 11.496094 19 10.78125 19 10 C 19 8.355469 17.644531 7 16 7 Z M 16 9 C 16.5625 9 17 9.4375 17 10 C 17 10.5625 16.5625 11 16 11 C 15.4375 11 15 10.5625 15 10 C 15 9.4375 15.4375 9 16 9 Z M 7.84375 15.09375 C 7.042969 15.230469 6.242188 15.507813 5.5 15.9375 C 2.164063 17.863281 1.011719 22.164063 2.9375 25.5 C 4.863281 28.835938 9.160156 29.988281 12.5 28.0625 C 14.410156 26.957031 15.441406 25.03125 15.75 23 L 20.1875 23 C 20.605469 24.15625 21.707031 25 23 25 C 24.644531 25 26 23.644531 26 22 C 26 20.355469 24.644531 19 23 19 C 21.707031 19 20.605469 19.84375 20.1875 21 L 14 21 L 14 22 C 14 23.726563 13.109375 25.414063 11.5 26.34375 C 9.097656 27.730469 6.042969 26.902344 4.65625 24.5 C 3.269531 22.097656 4.097656 19.042969 6.5 17.65625 C 7.03125 17.347656 7.585938 17.160156 8.15625 17.0625 Z M 9 21 C 9.5625 21 10 21.4375 10 22 C 10 22.5625 9.5625 23 9 23 C 8.4375 23 8 22.5625 8 22 C 8 21.4375 8.4375 21 9 21 Z M 23 21 C 23.5625 21 24 21.4375 24 22 C 24 22.5625 23.5625 23 23 23 C 22.4375 23 22 22.5625 22 22 C 22 21.4375 22.4375 21 23 21 Z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/webhooks" },
          },
          {
            name: "Components",
            description: "Inputs, Tables, Buttons, Modal Dialogs, Command Palette, Breadcrumbs, Banners...",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 1 9 L 1 10 L 1 23 L 31 23 L 31 9 L 1 9 z M 3 11 L 29 11 L 29 21 L 3 21 L 3 11 z M 5 17 L 5 19 L 7 19 L 7 17 L 5 17 z M 9 17 L 9 19 L 11 19 L 11 17 L 9 17 z M 13 17 L 13 19 L 15 19 L 15 17 L 13 17 z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/components" },
          },
          {
            name: "Roles & Permissions",
            description: "Roles, permissions for page views and actions + Groups, and row-level permissions for CRUD security.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 6 3 L 6 29 L 18 29 L 18 32 L 32 32 L 32 22 L 23 22 L 23 20 C 23 18.9 23.9 18 25 18 C 26.1 18 27 18.9 27 20 L 29 20 C 29 17.8 27.2 16 25 16 C 22.8 16 21 17.8 21 20 L 21 22 L 18 22 L 18 27 L 8 27 L 8 5 L 24 5 L 24 14 L 26 14 L 26 3 L 6 3 z M 11 8 L 11 10 L 17 10 L 17 8 L 11 8 z M 11 14 L 11 16 L 21 16 L 21 14 L 11 14 z M 11 18 L 11 20 L 19 20 L 19 18 L 11 18 z M 11 22 L 11 24 L 16 24 L 16 22 L 11 22 z M 20 24 L 30 24 L 30 30 L 20 30 L 20 24 z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/roles-and-permissions" },
          },
          {
            name: "CRM",
            description: "Manage your contacts, companies, and opportunities with custom properties. Built with the Entity Builder.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 16 5 A 2 2 0 0 0 15 8.7304688 L 15 13 L 17 13 L 17 8.7304688 A 2 2 0 0 0 16 5 z M 7 9 A 2 2 0 0 0 7 13 A 2 2 0 0 0 7.6289062 12.896484 L 10.917969 15.820312 C 11.275969 15.251312 11.722141 14.744219 12.244141 14.324219 L 8.9570312 11.402344 A 2 2 0 0 0 7 9 z M 25 9 A 2 2 0 0 0 23.042969 11.402344 L 19.755859 14.324219 C 20.277859 14.744219 20.724031 15.251312 21.082031 15.820312 L 24.371094 12.896484 A 2 2 0 0 0 25 13 A 2 2 0 0 0 25 9 z M 16 15 C 13.802666 15 12 16.802666 12 19 C 12 20.093626 12.448477 21.08799 13.167969 21.8125 C 11.31267 22.8355 10 24.740671 10 27 L 12 27 C 12 24.778188 13.778188 23 16 23 C 18.221812 23 20 24.778188 20 27 L 22 27 C 22 24.740671 20.68733 22.8355 18.832031 21.8125 C 19.551523 21.08799 20 20.093626 20 19 C 20 16.802666 18.197334 15 16 15 z M 5 17 A 2 2 0 0 0 5 21 A 2 2 0 0 0 6.7285156 20 L 10 20 L 10 18 L 6.7324219 18 A 2 2 0 0 0 5 17 z M 16 17 C 17.116666 17 18 17.883334 18 19 C 18 20.116666 17.116666 21 16 21 C 14.883334 21 14 20.116666 14 19 C 14 17.883334 14.883334 17 16 17 z M 27 17.005859 A 2 2 0 0 0 25.271484 18.003906 L 22.001953 18 L 21.998047 20 L 25.267578 20.003906 A 2 2 0 0 0 27 21.005859 A 2 2 0 0 0 27 17.005859 z"></path> </svg>`,
          },
          {
            name: "Page Blocks 🚧",
            description: "UNDER CONSTRUCTION: Update the landing page Hero, Features, Logo Clouds, Gallery, and more... Try setting ?editMode=true in the URL.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 4 5 L 4 13 L 28 13 L 28 5 Z M 6 7 L 26 7 L 26 11 L 6 11 Z M 8 8 C 7.449219 8 7 8.449219 7 9 C 7 9.550781 7.449219 10 8 10 C 8.550781 10 9 9.550781 9 9 C 9 8.449219 8.550781 8 8 8 Z M 11 8 C 10.449219 8 10 8.449219 10 9 C 10 9.550781 10.449219 10 11 10 C 11.550781 10 12 9.550781 12 9 C 12 8.449219 11.550781 8 11 8 Z M 14 8 C 13.449219 8 13 8.449219 13 9 C 13 9.550781 13.449219 10 14 10 C 14.550781 10 15 9.550781 15 9 C 15 8.449219 14.550781 8 14 8 Z M 4 14 L 4 27 L 28 27 L 28 14 L 26 14 L 26 25 L 6 25 L 6 14 Z M 8 15 L 8 23 L 16 23 L 16 15 Z M 18 15 L 18 17 L 24 17 L 24 15 Z M 10 17 L 14 17 L 14 21 L 10 21 Z M 18 18 L 18 20 L 24 20 L 24 18 Z M 18 21 L 18 23 L 24 23 L 24 21 Z"></path> </svg>`,
          },
          {
            name: "Events & Webhooks 🚀",
            description: "Trigger actions when certain events happen with internal or external webhooks to customize business logic.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 16 3 C 8.832031 3 3 8.832031 3 16 C 3 23.167969 8.832031 29 16 29 C 23.167969 29 29 23.167969 29 16 C 29 8.832031 23.167969 3 16 3 Z M 16 5 C 22.085938 5 27 9.914063 27 16 C 27 22.085938 22.085938 27 16 27 C 9.914063 27 5 22.085938 5 16 C 5 9.914063 9.914063 5 16 5 Z M 15 10 L 15 18 L 17 18 L 17 10 Z M 15 20 L 15 22 L 17 22 L 17 20 Z"></path> </svg>`,
            link: { text: "Learn more", href: "https://saasrock.com/docs/features/events-and-webhooks" },
          },
          {
            name: "Analytics 🚀",
            description: "Built-in analytics for page views and events tracking.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 4 4 L 4 21.667969 L 6 19.667969 L 6 12 L 26 12 L 26 26 L 8.1523438 26 L 6.1523438 28 L 28 28 L 28 4 L 4 4 z M 6 6 L 26 6 L 26 10 L 6 10 L 6 6 z M 7 7 L 7 9 L 9 9 L 9 7 L 7 7 z M 10 7 L 10 9 L 12 9 L 12 7 L 10 7 z M 13 7 L 13 9 L 25 9 L 25 7 L 13 7 z M 19.453125 17.041016 L 14.453125 22.041016 L 10.453125 18.041016 L 2.0136719 26.482422 L 3.4277344 27.896484 L 10.453125 20.871094 L 14.453125 24.871094 L 19.453125 19.871094 L 21.732422 22.148438 L 23.146484 20.734375 L 19.453125 17.041016 z"></path> </svg>`,
          },
          {
            name: "Email marketing 🚀",
            description: "Send emails to your contacts and track the email delivery, open, and click rates.",
            img: `<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="32" height="32" viewBox="0 0 32 32"> <path d="M 28 3.03125 L 26.40625 4.1875 C 26.40625 4.1875 24.417969 5.664063 21.5625 7.125 C 18.707031 8.585938 14.988281 10 11.71875 10 L 2 10 L 2 19.125 L 2.03125 19.28125 L 4.03125 26.28125 L 4.25 27 L 10.3125 27 L 9.96875 25.71875 L 8.34375 20 L 11.71875 20 C 14.945313 20 18.664063 21.441406 21.53125 22.90625 C 24.398438 24.371094 26.40625 25.8125 26.40625 25.8125 L 28 26.96875 L 28 17.8125 C 29.15625 17.394531 30 16.292969 30 15 C 30 13.707031 29.15625 12.605469 28 12.1875 Z M 26 6.75 L 26 23.21875 C 25.171875 22.660156 24.515625 22.152344 22.4375 21.09375 C 19.5 19.59375 15.707031 18.074219 12 18 L 12 12 C 15.742188 11.925781 19.539063 10.375 22.46875 8.875 C 24.542969 7.8125 25.179688 7.308594 26 6.75 Z M 4 12 L 10 12 L 10 18 L 4 18 Z M 4.34375 20 L 6.25 20 L 7.65625 25 L 5.75 25 Z"></path> </svg>`,
          },
        ],
      },
    },
    // Features #2
    {
      features: {
        style: defaultStyles.features,
        topText: "Powered by the best tools",
        headline: "First-class tech stack",
        subheadline: "The codebase comes with the latest technology out there: SSR, utility-first CSS, and first-class ORM.",
        columns: 3,
        items: [
          {
            name: "Remix",
            description: "Focused on web standards and modern web app UX, you’re simply going to build better websites.",
            link: { text: "Read docs", href: "https://remix.run/docs/en/v1" },
          },
          {
            name: "React",
            description: "A JavaScript library for building user interfaces.",
            link: { text: "Read docs", href: "https://reactjs.org/docs/getting-started.html" },
          },
          {
            name: "Tailwind CSS",
            description: "Rapidly build modern websites without ever leaving your HTML. The best utility-first CSS framework.",
            link: { text: "Read docs", href: "https://tailwindcss.com/docs/utility-first" },
          },
          {
            name: "Prisma",
            description: "Next-generation Node.js and TypeScript ORM.",
            link: { text: "Read docs", href: "https://www.prisma.io/docs" },
          },
        ],
      },
    },
    // Features #3
    {
      features: {
        style: defaultStyles.features,
        topText: "Connect with your apps",
        headline: "Integrations",
        subheadline: "Using Webhooks by Zapier, integrate with +4,000 apps, such as Notion, Airtable, Google Sheets/Docs, and more.",
        columns: 3,
        items: [
          {
            name: "Stripe",
            description: "The payments infrastructure for the internet. Stripe Customers, Products, and Prices.",
            link: { text: "Read docs", href: "https://stripe.com/docs?ref=remix-page-blocks" },
          },
          {
            name: "Postmark",
            description: "The email delivery service that people actually like. Customize your transactional email templates (Welcome, Forgot password...).",
            link: { text: "Read docs", href: "https://postmarkapp.com/developer?ref=remix-page-blocks" },
          },
          {
            name: "Webhooks by Zapier",
            description: "Hook with Zapier by using the Custom Entity events (Created, Updated, and Deleted).",
            link: { text: "Read docs", href: "https://platform.zapier.com/docs/zapier-intro?ref=remix-page-blocks" },
          },
          {
            name: "Deployment",
            description:
              "Deploy your Remix SaaS application on Vercel, Netlify, Cloudflare Workers, Fly.io, or use your own server (this site uses Vercel + Supabase).",
            link: { text: "Read docs", href: "https://remix.run/docs/en/v1/guides/deployment?ref=remix-page-blocks" },
          },
        ],
      },
    },
    // Newsletter
    {
      newsletter: {
        style: defaultStyles.newsletter,
        headline: "Stay up to date",
        subheadline: "Subscribe to the newsletter to get product updates",
      },
    },
    // Faq
    {
      faq: {
        style: defaultStyles.faq,
        items: [
          {
            question: "How do I get the code after purchasing?",
            answer:
              "You will be invited to the saasrock-core repository on GitHub. If you bought SaasRock Enterprise you will also be invited to the saasrock-enterprise repository.",
          },
          {
            question: "Will there be updates every month?",
            answer: "No, I can't guarantee that, but I'll try. What you can do is pausing your subscription and come back when you see a shiny new feature.",
          },
          {
            question: "Can I get a refund?",
            answer: "Due to the nature of software development being a custom service, we do not offer refunds.",
          },
          {
            question: "Is it really a perpetual license for unlimited websites?",
            answer:
              "Yes, you don't need a subscription to use SaasRock for your SaaS app development. Subscription is only required to get access to the private repository to get updates.",
          },
          {
            question: "Will I still get updates after my subscription expires?",
            answer: "No, you could subscribe again to get the latest updates.",
          },
          {
            question: "What is a developer license?",
            answer:
              "A developer license is a license for a developer to use SaasRock for their own SaaS app development. If you need a license for your team, buy all the licenses you need.",
            link: { text: "shared.readMore", href: "https://saasrock.com/docs/license" },
          },
        ],
      },
    },
    // Footer
    {
      footer: defaultFooter,
    },
  ];
  return blocks;
}

const defaultHeader: HeaderBlockDto = {
  style: HeaderBlockStyle.simple,
  withLogo: true,
  withSignInAndSignUp: true,
  withThemeSwitcher: true,
  withLanguageSwitcher: true,
  links: [
    { path: "https://saasrock.com/?ref=remix-page-blocks-saasrock-template-header", title: "Product", target: "_blank" },
    { path: "https://saasrock.com/pricing?ref=remix-page-blocks-saasrock-template-header", title: "Pricing", target: "_blank" },
    { path: "https://saasrock.com/docs?ref=remix-page-blocks-saasrock-template-header", title: "Docs", className: "", target: "_blank" },
    {
      title: "About",
      items: [
        { path: "https://saasrock.com/blog?ref=remix-page-blocks-saasrock-template-header", title: "Blog", target: "_blank" },
        { path: "https://saasrock.com/changelog?ref=remix-page-blocks-saasrock-template-header", title: "Changelog", target: "_blank" },
        { path: "https://saasrock.com/docs/roadmap?ref=remix-page-blocks-saasrock-template-header", title: "Roadmap", target: "_blank" },
        { path: "https://saasrock.com/contact?ref=remix-page-blocks-saasrock-template-header", title: "Contact", target: "_blank" },
        { path: "https://saasrock.com/newsletter?ref=remix-page-blocks-saasrock-template-header", title: "Newsletter", target: "_blank" },
      ],
    },
  ],
};

export const defaultFooter: FooterBlockDto = {
  style: FooterBlockStyle.columns,
  text: "Quick start your MVP with out-of-the-box SaaS features like Authentication, Pricing & Subscriptions, Admin & App portals, Entity Builder (Autogenerated CRUD, API, Webhooks, Permissions, Audit-trails...), Blogging, CRM, Email Marketing, and more. Don't reinvent the wheel, again.",
  sections: [
    {
      name: "Application",
      items: [
        { name: "Pricing", href: "https://saasrock.com/pricing?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Sign in", href: "https://saasrock.com/login?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Sign up", href: "https://saasrock.com/register?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Blog", href: "https://saasrock.com/blog?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Docs", href: "https://saasrock.com/docs?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
      ],
    },
    {
      name: "Product",
      items: [
        { name: "Contact", href: "https://saasrock.com/contact?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Newsletter", href: "https://saasrock.com/newsletter?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Changelog", href: "https://saasrock.com/changelog?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Terms and Conditions", href: "https://saasrock.com/terms-and-conditions?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
        { name: "Privacy Policy", href: "https://saasrock.com/privacy-policy?ref=remix-page-blocks-saasrock-template-footer", target: "_blank" },
      ],
    },
  ],
  socials: {
    instagram: "saas_rock",
    twitter: "saas_rock",
    github: "AlexandroMtzG",
    discord: "invite/KMkjU2BFn9",
  },
};
