import { MarketingFeatureDto, MarketingFeatureStatus, MarketingFeatureType } from "~/application/dtos/marketing/MarketingFeatureDto";
import { TestimonialDto } from "~/application/dtos/marketing/TestimonialDto";

export function getTestimonials(): TestimonialDto[] {
  return [
    {
      role: "CEO",
      company: "Piloterr",
      companyUrl: "https://www.piloterr.com/",
      logoLightMode: "https://yahooder.sirv.com/saasrock/testimonials/piloterr-light.png",
      logoDarkMode: "https://yahooder.sirv.com/saasrock/testimonials/piloterr-dark.png",
      name: "Josselin Liebe",
      personalWebsite: "https://josselinlie.be/",
      avatar: "https://avatars.githubusercontent.com/u/15314417?v=4",
      quote: "You've already solved 90% of my problems with your project :)",
    },
  ];
}

export function getAllFeatures(): MarketingFeatureDto[] {
  return [...getFeatures(), ...getUpcomingFeatures()];
}

export function getFeatures(): MarketingFeatureDto[] {
  return [
    {
      type: MarketingFeatureType.Core,
      name: "Admin Portal",
      status: MarketingFeatureStatus.Done,
      description: "Manage your SaaS tenants, users, blog, entities, audit trails, API Keys, pricing, and emails.",
      link: "/docs/features/admin-portal",
    },
    {
      type: MarketingFeatureType.Core,
      name: "App Portal",
      status: MarketingFeatureStatus.Done,
      description: "Your customer's portal with Dashboard and Settings pages: Profile, Members, Subscription, API Keys...",
      link: "/docs/features/app-portal",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Authentication",
      status: MarketingFeatureStatus.Done,
      description: "Login, Register, and Forgot/Reset password auth pages + Multi-tenancy support.",
      link: "/docs/features/authentication",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Subscriptions",
      status: MarketingFeatureStatus.Done,
      description: "Subscription plans/prices with Flat-rate and Per-seat pricing models.",
      link: "/docs/features/subscriptions",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Blogging",
      status: MarketingFeatureStatus.Done,
      description: "Publish your blog posts with SEO-ready features.",
      link: "/docs/features/blogging",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Audit Trails",
      status: MarketingFeatureStatus.Done,
      description: "Track the SaaS application usage with Created, Updated, and Deleted events.",
      link: "/docs/features/audit-trails",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Entity Builder",
      status: MarketingFeatureStatus.Done,
      description: "Create custom entities/properties with autogenerated views, forms, API, audit trails, and webhooks.",
      link: "/docs/features/entity-builder",
    },
    {
      type: MarketingFeatureType.Core,
      name: "API",
      status: MarketingFeatureStatus.Done,
      description: "Let your SaaS users use the API to integrate with other services.",
      link: "/docs/features/api",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Entity Webhooks",
      status: MarketingFeatureStatus.Done,
      description: "Connect with Zappier, hence with +4,000 popular applications like Google Drive, Notion, Asana...",
      link: "/docs/features/webhooks",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Components",
      status: MarketingFeatureStatus.Done,
      description: "Inputs, Tables, Buttons, Modal Dialogs, Command Palette, Breadcrumbs, Banners...",
      link: "/docs/components",
    },
    {
      type: MarketingFeatureType.Core,
      name: "Roles & Permissions",
      status: MarketingFeatureStatus.Done,
      description: "Roles, permissions for page views and actions + Groups, and row-level permissions for CRUD security.",
      link: "/docs/features/roles-and-permissions",
    },
    {
      type: MarketingFeatureType.Enterprise,
      name: "Events & Webhooks",
      status: MarketingFeatureStatus.Done,
      description: "Trigger actions when certain events happen with internal or external webhooks to customize business logic.",
      link: "/docs/features/events-and-webhooks",
    },
    {
      type: MarketingFeatureType.Core,
      name: "CRM",
      status: MarketingFeatureStatus.Done,
      description: "Manage your contacts, companies, and opportunities with custom properties. Built with the Entity Builder.",
    },
    {
      type: MarketingFeatureType.Enterprise,
      name: "Email marketing",
      status: MarketingFeatureStatus.Done,
      description: "Send emails to your contacts and track the email delivery, open, and click rates.",
    },
  ];
}

export function getUpcomingFeatures(): MarketingFeatureDto[] {
  return [
    {
      status: MarketingFeatureStatus.Done,
      name: "Workflows",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://www.salesforce.com/editions-pricing/sales-cloud/",
          price: "$150/month",
        },
      ],
      save: 150,
    },
    {
      status: MarketingFeatureStatus.Done,
      name: "Events & Webhooks",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://www.g2.com/products/zapier/pricing",
          price: "$19/month",
        },
      ],
      save: 19,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Internationalization",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://www.transifex.com/pricing/",
          price: "$105/month",
        },
      ],

      save: 105,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Feature Flags",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://flagsmith.com/pricing/",
          price: "$45/month",
        },
      ],
      save: 45,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Affiliate + Referral manager",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://tapfiliate.com/pricing/",
          price: "$149/month",
        },
      ],

      save: 149,
    },
    {
      status: MarketingFeatureStatus.Done,
      name: "Advanced CRM",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://www.salesforce.com/products/sales-cloud/pricing",
          price: "$75/user/month",
        },
      ],

      save: 75,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Advanced Blogging",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://ghost.org/pricing/",
          price: "$31/month",
        },
      ],
      save: 31,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "HelpDesk",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://www.intercom.com/pricing",
          price: "$300/month",
        },
      ],

      save: 300,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Knowledge Base Features",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://document360.com/pricing/",
          price: "$299/month",
        },
      ],
      save: 299,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Single Sign-On",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://workos.com/pricing",
          price: "$49/month",
        },
      ],
      save: 49,
    },
    {
      status: MarketingFeatureStatus.UnderReview,
      name: "Built-in Demo",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://www.demostack.com/",
          price: "?",
        },
        {
          site: "https://saleo.io/",
          price: "?",
        },
      ],

      save: 100,
    },
    {
      status: MarketingFeatureStatus.Planned,
      name: "Onboarding",
      type: MarketingFeatureType.Enterprise,
      description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
      platforms: [
        {
          site: "https://arrows.to/pricing/",
          price: "$99/month",
        },
      ],

      save: 99,
    },
    // {
    //   status: MarketingFeatureStatus.UnderReview,
    //   name: "Product Text Editing",
    //   type: MarketingFeatureType.Enterprise,
    //   description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
    //   platforms: [
    //     {
    //       site: "https://www.flycode.com/pricing",
    //       price: "$79/month",
    //     },
    //   ],

    //   save: 79,
    // },
    // {
    //   status: MarketingFeatureStatus.UnderReview,
    //   name: "Accessibility",
    //   type: MarketingFeatureType.Enterprise,
    //   description: "Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.",
    //   platforms: [
    //     {
    //       site: "https://accessibe.com/pricing",
    //       price: "$149/month",
    //     },
    //   ],

    //   save: 149,
    // },
  ];
}
